export interface Tool {
  name: string;
  description: string;
  slug: string;
  icon: string;
  category: string;
  categorySlug: string;
  color: string;
}

export function getToolUrl(tool: { categorySlug?: string; slug: string }): string {
  return "/tools/" + (tool.categorySlug || "organize-pdf") + "/" + tool.slug;
}

export interface ToolCategory {
  name: string;
  slug: string;
  description: string;
  icon: string;
}

export const CATEGORIES: ToolCategory[] = [
  { name: "Convert from PDF", slug: "convert-from-pdf", description: "Convert PDF files to Word, JPG, Excel, PowerPoint, Text, and HTML.", icon: "🔄" },
  { name: "Convert to PDF", slug: "convert-to-pdf", description: "Convert Images, Office documents, and Text to high-quality PDF.", icon: "📄" },
  { name: "Organize PDF", slug: "organize-pdf", description: "Merge, split, remove, rotate, and rearrange PDF document pages.", icon: "📑" },
  { name: "Optimize PDF", slug: "optimize-pdf", description: "Compress, repair, OCR, and optimize PDF files for fast sharing.", icon: "🗜️" },
  { name: "Edit PDF", slug: "edit-pdf", description: "Add text, watermarks, page numbers, and crop PDF pages.", icon: "✏️" },
  { name: "PDF Security", slug: "pdf-security", description: "Sign, encrypt with password, unlock, and redact PDF files.", icon: "🔒" },
  { name: "Office", slug: "office", description: "Process Word, Excel, and PowerPoint documents without Microsoft Office.", icon: "📊" },
  { name: "Media", slug: "media", description: "Compress, convert, and resize images in your browser privately.", icon: "🖼️" },
  { name: "Calculators", slug: "calculators", description: "Fast calculations for finance, health, academics, and units.", icon: "🧮" },
  { name: "Developer", slug: "developer", description: "Inspect, format, encode, and decode developer payloads.", icon: "💻" },
  { name: "Text", slug: "text", description: "Word count, case conversion, and text cleaning utilities.", icon: "📝" },
  { name: "Design", slug: "design", description: "Color palettes, shadows, QR codes, and resume generation.", icon: "🎨" },
];

export const tools: Tool[] = [
  // ─── PDF Suite (Inspired by iLovePDF & PDF24) ───
  {
    name: 'Sign PDF (E-Signature)',
    description: 'Draw or type your digital signature and place it anywhere on your PDF document. 100% legal & private.',
    slug: 'sign-pdf',
    icon: '✍️',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-blue-600 to-indigo-700',
  },
  {
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document with reordering. 100% private.',
    slug: 'merge-pdf',
    icon: '📎',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-red-500 to-rose-600',
  },
  {
    name: 'Split PDF',
    description: 'Extract specific pages from a PDF or split every page into separate files visually.',
    slug: 'split-pdf',
    icon: '✂️',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-orange-500 to-amber-600',
  },
  {
    name: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining document clarity for email attachments and portal uploads.',
    slug: 'compress-pdf',
    icon: '🗜️',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-rose-500 to-red-600',
  },
  {
    name: 'Compress PDF to 100KB',
    description: 'Shrink PDF documents under 100 KB for government recruitment, visa, and admission portals.',
    slug: 'compress-pdf-to-100kb',
    icon: '🎯',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-red-500 to-rose-600',
  },
  {
    name: 'Compress PDF to 200KB',
    description: 'Compress PDF files below 200 KB for online job applications, civil exams, and portal compliance.',
    slug: 'compress-pdf-to-200kb',
    icon: '📉',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-rose-600 to-pink-600',
  },
  {
    name: 'Compress PDF to 500KB',
    description: 'Maintain high print-ready resolution while shrinking heavy PDFs under 500 KB.',
    slug: 'compress-pdf-to-500kb',
    icon: '📊',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-amber-600 to-red-600',
  },
  {
    name: 'Image to PDF',
    description: 'Convert JPG, PNG, and WebP images into clean, formatted PDF documents.',
    slug: 'image-to-pdf',
    icon: '🖼️',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-sky-500 to-blue-600',
  },
  {
    name: 'PDF to JPG',
    description: 'Convert PDF document pages into high-resolution JPG images for presentations and sharing.',
    slug: 'pdf-to-jpg',
    icon: '📷',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-emerald-500 to-teal-600',
  },
  {
    name: 'PDF to Text Extractor',
    description: 'Extract plain text from PDF pages for research, study notes, and speech-to-text.',
    slug: 'pdf-to-text',
    icon: '📜',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-amber-600 to-orange-600',
  },
  {
    name: 'Text & Notes to PDF',
    description: 'Turn written text, essays, meeting notes, and letters into clean, formatted PDF documents.',
    slug: 'text-to-pdf',
    icon: '📝',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-cyan-600 to-blue-600',
  },
  {
    name: 'Redact PDF (Blackout)',
    description: 'Permanently blackout confidential text, bank numbers, and sensitive details on PDF pages.',
    slug: 'redact-pdf',
    icon: '⬛',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-gray-700 to-slate-900',
  },
  {
    name: 'Crop PDF',
    description: 'Trim excess page margins and crop page dimensions for printing or handheld reading.',
    slug: 'crop-pdf',
    icon: '📐',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-teal-600 to-emerald-700',
  },
  {
    name: 'Scan to PDF',
    description: 'Capture document pages using your webcam or photos and compile into a scanned PDF.',
    slug: 'scan-to-pdf',
    icon: '📠',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-violet-600 to-indigo-600',
  },
  {
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90°, 180°, or 270° clockwise or counter-clockwise.',
    slug: 'rotate-pdf',
    icon: '🔃',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-emerald-500 to-green-600',
  },
  {
    name: 'Add Watermark to PDF',
    description: 'Add custom text watermarks with transparency, angle, and position controls.',
    slug: 'watermark-pdf',
    icon: '💧',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-cyan-500 to-teal-600',
  },
  {
    name: 'Remove PDF Pages',
    description: 'Delete unwanted pages from any PDF document and download the cleaned version.',
    slug: 'remove-pdf-pages',
    icon: '🗑️',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-rose-600 to-red-700',
  },
  {
    name: 'Add Page Numbers to PDF',
    description: 'Insert header or footer page numbers (e.g. Page X of Y) into PDF documents.',
    slug: 'number-pdf',
    icon: '🔢',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-blue-600 to-indigo-600',
  },
  {
    name: 'PDF Metadata Editor',
    description: 'View and update PDF metadata: Title, Author, Subject, Keywords, and Creator.',
    slug: 'pdf-metadata',
    icon: '🏷️',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-purple-600 to-violet-700',
  },

  // ─── Student, Teacher & Career Essentials ───
  {
    name: 'GPA & Grade Calculator',
    description: 'Calculate semester and cumulative GPA on 4.0 scale with weighted credit hours for students & teachers.',
    slug: 'gpa-calculator',
    icon: '🎓',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-indigo-600 to-purple-600',
  },
  {
    name: 'Resume & CV Builder',
    description: 'Build modern, ATS-friendly resumes for students, teachers, and employees with instant PDF export.',
    slug: 'resume-builder',
    icon: '💼',
    category: "Design",
    categorySlug: "design",
    color: 'from-emerald-600 to-teal-700',
  },

  // ─── Image & Media Tools ───
  {
    name: 'Image Compressor',
    description: 'Compress PNG, JPG, and WebP images in your browser with live before/after preview.',
    slug: 'image-compressor',
    icon: '🗜️',
    category: "Media",
    categorySlug: "media",
    color: 'from-rose-500 to-pink-500',
  },
  {
    name: 'Image Resizer',
    description: 'Resize image dimensions by custom width, height, or percentage while maintaining aspect ratio.',
    slug: 'image-resizer',
    icon: '📐',
    category: "Media",
    categorySlug: "media",
    color: 'from-indigo-500 to-purple-600',
  },
  {
    name: 'Image Converter',
    description: 'Convert images between PNG, JPG, WebP, and BMP instantly in your browser.',
    slug: 'image-converter',
    icon: '🔄',
    category: "Media",
    categorySlug: "media",
    color: 'from-amber-500 to-orange-600',
  },
  {
    name: 'Image Color Picker & Eyedropper',
    description: 'Upload any photo and click anywhere to sample, inspect, and copy Hex and RGB colors.',
    slug: 'image-color-picker',
    icon: '🎯',
    category: "Media",
    categorySlug: "media",
    color: 'from-teal-500 to-emerald-600',
  },
  {
    name: 'SVG Viewer & Optimizer',
    description: 'Inspect, preview, clean, and minify raw SVG vector code with syntax highlighting.',
    slug: 'svg-viewer-optimizer',
    icon: '⚡',
    category: "Media",
    categorySlug: "media",
    color: 'from-cyan-500 to-blue-500',
  },
  {
    name: 'Favicon Generator',
    description: 'Generate standard website favicons (16x16, 32x32, 48x48, 180x180 Apple Touch) from an image.',
    slug: 'favicon-generator',
    icon: '⭐',
    category: "Media",
    categorySlug: "media",
    color: 'from-yellow-500 to-amber-600',
  },

  // ─── Developer & Security Tools ───
  {
    name: 'JSON Formatter',
    description: 'Format, validate, and minify JSON data with line & column syntax diagnostics.',
    slug: 'json-formatter',
    icon: '{ }',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-blue-500 to-cyan-500',
  },
  {
    name: 'JWT Decoder & Inspector',
    description: 'Decode JSON Web Tokens (Header, Payload, Claims, Expiration) client-side securely.',
    slug: 'jwt-decoder',
    icon: '🔑',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-violet-600 to-purple-700',
  },
  {
    name: 'UUID / GUID Generator',
    description: 'Generate standard Version-4 UUIDs in bulk (1 to 1000) with hyphens and uppercase options.',
    slug: 'uuid-generator',
    icon: '🆔',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-emerald-500 to-teal-600',
  },
  {
    name: 'Code Beautifier & Minifier',
    description: 'Beautify or minify HTML, CSS, and JavaScript code snippets for clean formatting.',
    slug: 'code-beautifier-minifier',
    icon: '</>',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-blue-600 to-indigo-700',
  },
  {
    name: 'SQL Query Formatter',
    description: 'Format and indent SQL queries (SELECT, INSERT, UPDATE, JOINs) for readability.',
    slug: 'sql-formatter',
    icon: '🗄️',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-cyan-600 to-blue-700',
  },
  {
    name: 'Cron Expression Generator',
    description: 'Build cron schedules visually and understand what cron syntax means in plain English.',
    slug: 'cron-generator',
    icon: '⏰',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-amber-600 to-red-600',
  },
  {
    name: 'Regex Tester',
    description: 'Test regular expressions with real-time flag customization and group capture parsing.',
    slug: 'regex-tester',
    icon: '.*',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-yellow-500 to-orange-500',
  },
  {
    name: 'Base64 Encoder / Decoder',
    description: 'Encode and decode Base64 strings with byte size statistics and quick swap.',
    slug: 'base64-encoder-decoder',
    icon: '🔄',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-indigo-500 to-blue-500',
  },
  {
    name: 'URL Encoder / Decoder',
    description: 'Encode and decode URLs and inspect query parameters in a formatted table.',
    slug: 'url-encoder-decoder',
    icon: '🔗',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-violet-500 to-purple-500',
  },
  {
    name: 'Timestamp Converter',
    description: 'Convert Unix epoch timestamps to human-readable dates across international timezones.',
    slug: 'timestamp-converter',
    icon: '⏱️',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-pink-500 to-rose-500',
  },
  {
    name: 'Password Generator',
    description: 'Generate strong, secure passwords with custom lengths, character sets, and bulk export.',
    slug: 'password-generator',
    icon: '🔐',
    category: "Design",
    categorySlug: "design",
    color: 'from-green-500 to-emerald-500',
  },
  {
    name: 'Hash Generator',
    description: 'Compute SHA-256, SHA-1, SHA-384, and SHA-512 cryptographic hashes for text and files.',
    slug: 'hash-generator',
    icon: '#️⃣',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-slate-600 to-gray-800',
  },

  // ─── Design, CSS & Styling ───
  {
    name: 'Color Palette Generator',
    description: 'Generate complementary, analogous, and triadic color schemes with spacebar & CSS export.',
    slug: 'color-palette-generator',
    icon: '🎨',
    category: "Design",
    categorySlug: "design",
    color: 'from-orange-500 to-red-500',
  },
  {
    name: 'CSS Box Shadow & Glassmorphism',
    description: 'Visual sliders for box shadows, blur, spread, elevation, and frosted glass CSS code.',
    slug: 'css-box-shadow-generator',
    icon: '🧊',
    category: "Design",
    categorySlug: "design",
    color: 'from-fuchsia-500 to-pink-600',
  },
  {
    name: 'Aspect Ratio Calculator',
    description: 'Calculate 16:9, 4:3, 1:1, 9:16 aspect ratios, scaling dimensions, and crop pixel values.',
    slug: 'aspect-ratio-calculator',
    icon: '📏',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-teal-600 to-cyan-700',
  },
  {
    name: 'QR Code Generator',
    description: 'Generate custom QR codes for URLs, WiFi credentials, emails, and vCards with color themes.',
    slug: 'qr-code-generator',
    icon: '📱',
    category: "Design",
    categorySlug: "design",
    color: 'from-purple-500 to-pink-500',
  },

  // ─── Text, Content & Data ───
  {
    name: 'Word Counter & Analyzer',
    description: 'Count words, characters, sentences, reading ease grade, and keyword density.',
    slug: 'word-counter',
    icon: '📝',
    category: "Text",
    categorySlug: "text",
    color: 'from-teal-500 to-cyan-500',
  },
  {
    name: 'Case Converter',
    description: 'Convert text to UPPERCASE, lowercase, Title Case (AP style), camelCase, snake_case, etc.',
    slug: 'case-converter',
    icon: 'Aa',
    category: "Text",
    categorySlug: "text",
    color: 'from-fuchsia-500 to-purple-600',
  },
  {
    name: 'Text Diff Checker',
    description: 'Compare two text versions side by side with line numbers and added/removed indicators.',
    slug: 'text-diff-checker',
    icon: '🔍',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-lime-500 to-green-600',
  },
  {
    name: 'Markdown Preview',
    description: 'Live split-pane markdown editor with instant HTML formatting and sample preview.',
    slug: 'markdown-preview',
    icon: '📖',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-gray-600 to-gray-800',
  },
  {
    name: 'Lorem Ipsum Generator',
    description: 'Generate dummy placeholder text by words, sentences, or paragraphs with copy feedback.',
    slug: 'lorem-ipsum-generator',
    icon: '📄',
    category: "Text",
    categorySlug: "text",
    color: 'from-amber-500 to-orange-500',
  },
  {
    name: 'CSV to JSON & JSON to CSV',
    description: 'Convert spreadsheets and tabular CSV data into JSON arrays and vice versa instantly.',
    slug: 'csv-json-converter',
    icon: '📊',
    category: "Developer",
    categorySlug: "developer",
    color: 'from-emerald-600 to-green-700',
  },
  {
    name: 'List Cleaner & Deduplicator',
    description: 'Sort lists, remove duplicate lines, trim whitespace, and add prefixes or suffixes.',
    slug: 'list-cleaner',
    icon: '📋',
    category: "Text",
    categorySlug: "text",
    color: 'from-indigo-600 to-blue-600',
  },

  // ─── Math, Finance & Calculations ───
  {
    name: 'Universal Unit Converter',
    description: 'Convert Length, Weight, Temperature, Digital Data (Bytes, MB, GB), Area, and Speed.',
    slug: 'unit-converter',
    icon: '⚖️',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-sky-500 to-indigo-600',
  },
  {
    name: 'Percentage Calculator',
    description: 'Calculate what is X% of Y, percentage increase/decrease, and fraction conversions.',
    slug: 'percentage-calculator',
    icon: '%',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-purple-500 to-pink-600',
  },
  {
    name: 'Loan & Mortgage EMI Calculator',
    description: 'Calculate monthly loan EMI, total interest payable, and breakdown amortization table.',
    slug: 'loan-calculator',
    icon: '🏦',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-emerald-600 to-teal-700',
  },
  {
    name: 'Age Calculator',
    description: 'Calculate your exact age in years, months, days, hours, and next birthday countdown.',
    slug: 'age-calculator',
    icon: '🎂',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-amber-500 to-rose-500',
  },
  {
    name: 'BMI Calculator',
    description: 'Calculate Body Mass Index (BMI), health category, and healthy ideal weight range.',
    slug: 'bmi-calculator',
    icon: '🏃',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-teal-500 to-emerald-600',
  },
  {
    name: 'Weight, Calorie & BMR Calculator',
    description: 'Calculate Basal Metabolic Rate (BMR) and daily maintenance calories for weight loss or gain.',
    slug: 'calorie-bmr-calculator',
    icon: '🔥',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-orange-500 to-red-600',
  },
  {
    name: 'SIP Calculator',
    description: 'Calculate mutual fund SIP returns, total investment growth, and compounding wealth accumulation.',
    slug: 'sip-calculator',
    icon: '📈',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-indigo-600 to-emerald-600',
  },
  {
    name: 'Compound Interest Calculator',
    description: 'Calculate daily, monthly, and yearly compound interest on investments with recurring deposits.',
    slug: 'compound-interest-calculator',
    icon: '💹',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-emerald-600 to-teal-700',
  },
  {
    name: 'GST & Sales Tax Calculator',
    description: 'Calculate and add or remove GST, CGST, SGST, and IGST for tax invoices and billing in real time.',
    slug: 'gst-calculator',
    icon: '🧾',
    category: "Calculators",
    categorySlug: "calculators",
    color: 'from-amber-500 to-orange-600',
  },
  // ─── PDF24 Super Suite Additions ───
  {
    name: 'Invoice Generator',
    description: 'Create and download professional PDF invoices and receipts with line items, tax, and currency.',
    slug: 'create-invoice',
    icon: '🧾',
    category: "Office",
    categorySlug: "office",
    color: 'from-sky-500 to-indigo-600',
  },
  {
    name: 'Flatten PDF',
    description: 'Lock fillable form fields, checkboxes, and signatures into static read-only PDF graphics.',
    slug: 'flatten-pdf',
    icon: '🔒',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-amber-500 to-red-600',
  },
  {
    name: 'Pages Per Sheet (N-Up)',
    description: 'Put 2 or 4 pages side-by-side on a single printed sheet to save paper for lecture slides and handouts.',
    slug: 'nup-pdf',
    icon: '🖨️',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-emerald-500 to-teal-600',
  },
  {
    name: 'Rearrange PDF Pages',
    description: 'Visually sort, reorder, and reverse pages in any multi-page PDF document.',
    slug: 'rearrange-pdf-pages',
    icon: '📑',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-blue-500 to-indigo-600',
  },
  {
    name: 'Extract Images from PDF',
    description: 'Extract all photos, diagrams, and figures from your PDF documents as high-resolution PNGs.',
    slug: 'extract-pdf-images',
    icon: '🖼️',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-purple-500 to-pink-600',
  },
  {
    name: 'Edit PDF',
    description: 'Add text, shapes, highlighter annotations, and stamps directly onto PDF pages.',
    slug: 'edit-pdf',
    icon: '✏️',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-amber-500 to-yellow-600',
  },
  {
    name: 'Universal PDF Converter',
    description: 'Convert PDF to Word, Text, HTML, and Images, or convert files into PDF format.',
    slug: 'pdf-converter',
    icon: '🔄',
    category: "Office",
    categorySlug: "office",
    color: 'from-indigo-600 to-blue-700',
  },
  {
    name: 'Protect PDF (Password & Lock)',
    description: 'Encrypt your PDF with password security and restrict printing, copying, or editing.',
    slug: 'protect-pdf',
    icon: '🔒',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-emerald-600 to-teal-700',
  },
  {
    name: 'Unlock PDF',
    description: 'Remove passwords and permissions security from protected PDF documents.',
    slug: 'unlock-pdf',
    icon: '🔓',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-rose-500 to-pink-600',
  },
  {
    name: 'Extract PDF Pages',
    description: 'Visually pick specific page numbers or ranges to extract into a new PDF or ZIP file.',
    slug: 'extract-pdf-pages',
    icon: '📑',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-purple-600 to-indigo-600',
  },
  {
    name: 'Webpage & HTML to PDF',
    description: 'Convert live webpages or custom HTML/CSS code into clean, paginated PDF documents.',
    slug: 'webpage-to-pdf',
    icon: '🌐',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-blue-500 to-cyan-600',
  },
  {
    name: 'PDF OCR (Text Recognition)',
    description: 'Recognize and extract text from scanned documents and create searchable PDFs.',
    slug: 'pdf-ocr',
    icon: '👁️',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-cyan-600 to-teal-700',
  },
  {
    name: 'PDF Overlay & Letterhead',
    description: 'Stamp stationery, company letterhead, or watermark templates onto another PDF.',
    slug: 'overlay-pdf',
    icon: '📄',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-violet-600 to-purple-700',
  },
  {
    name: 'Compare PDFs',
    description: 'Side-by-side visual and text diff comparison between two PDF document revisions.',
    slug: 'compare-pdf',
    icon: '⚖️',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-orange-500 to-amber-600',
  },
  {
    name: 'Web Optimize PDF',
    description: 'Linearize, compress streams, and remove bloated metadata for fast web viewing.',
    slug: 'optimize-pdf-web',
    icon: '⚡',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-teal-500 to-emerald-600',
  },
  {
    name: 'Create PDF from Scratch',
    description: 'Design custom PDF documents with rich headings, paragraphs, tables, images, and signatures.',
    slug: 'create-pdf',
    icon: '🪄',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-rose-600 to-red-600',
  },
  {
    name: 'Repair PDF',
    description: 'Repair corrupted or damaged PDF documents by fixing xref tables, stream headers, and object catalogs.',
    slug: 'repair-pdf',
    icon: '🩹',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-amber-500 to-orange-600',
  },
  {
    name: 'Rasterize PDF',
    description: 'Convert PDF pages into high-resolution flattened images to permanently lock content and eliminate selectable vector layers.',
    slug: 'rasterize-pdf',
    icon: '🧱',
    category: "Optimize PDF",
    categorySlug: "optimize-pdf",
    color: 'from-slate-600 to-zinc-700',
  },
  {
    name: 'PDF to PDF/A',
    description: 'Convert standard PDF documents into ISO-compliant PDF/A format for long-term archiving and legal preservation.',
    slug: 'pdf-to-pdfa',
    icon: '🏛️',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-blue-600 to-indigo-700',
  },
  {
    name: 'Halve PDF Pages',
    description: 'Split two-page book spreads and side-by-side scans into individual single pages vertically or horizontally.',
    slug: 'halve-pdf-pages',
    icon: '📖',
    category: "Organize PDF",
    categorySlug: "organize-pdf",
    color: 'from-emerald-600 to-teal-700',
  },
  {
    name: 'Change PDF Page Size',
    description: 'Resize and rescale PDF pages to standard paper formats like A4, US Letter, A3, Legal, or custom dimensions.',
    slug: 'change-pdf-page-size',
    icon: '📐',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-indigo-500 to-purple-600',
  },
  {
    name: 'Fill Out PDF Form',
    description: 'Interactively fill in text fields, checkboxes, and radio buttons on official PDF forms and export filled PDFs.',
    slug: 'fill-pdf-form',
    icon: '📝',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-teal-600 to-emerald-700',
  },
  {
    name: 'Create Fillable PDF',
    description: 'Design and add interactive form fields (text boxes, checkboxes, dropdowns) to any static PDF document.',
    slug: 'create-fillable-pdf',
    icon: '📋',
    category: "PDF Security",
    categorySlug: "pdf-security",
    color: 'from-sky-600 to-blue-700',
  },
  {
    name: 'Bookmark PDF',
    description: 'Create, edit, and organize hierarchical bookmarks and table of contents outlines for PDF navigation.',
    slug: 'bookmark-pdf',
    icon: '🔖',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-rose-500 to-pink-600',
  },
  {
    name: 'PDF Reader & Viewer',
    description: 'Read and view PDF documents online with smooth page navigation, zooming, thumbnails, search, and presentation mode.',
    slug: 'pdf-reader',
    icon: '👓',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-blue-500 to-cyan-600',
  },
  {
    name: 'PDF Viewer Preferences',
    description: 'Configure default opening preferences: zoom level, single/two-page spread, fullscreen, and menu bar visibility.',
    slug: 'set-pdf-viewer-preferences',
    icon: '⚙️',
    category: "Edit PDF",
    categorySlug: "edit-pdf",
    color: 'from-violet-500 to-indigo-600',
  },
  {
    name: 'PDF to Markdown',
    description: 'Convert PDF documents into structured Markdown (.md) with headings, bullet points, tables, and formatted text.',
    slug: 'pdf-to-markdown',
    icon: '⬇️',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-orange-600 to-red-600',
  },
  {
    name: 'Markdown to PDF',
    description: 'Render formatted Markdown with headers, code blocks, tables, and typography into clean, publication-ready PDFs.',
    slug: 'markdown-to-pdf',
    icon: '⬆️',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-fuchsia-600 to-pink-700',
  },
  {
    name: 'PDF to HTML',
    description: 'Convert PDF pages into modern, responsive HTML web pages with clean typography and layout preservation.',
    slug: 'pdf-to-html',
    icon: '🌐',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-amber-500 to-yellow-600',
  },
  {
    name: 'PDF to PNG',
    description: 'Convert PDF pages into transparent or white background high-res PNG images with 1-click batch ZIP export.',
    slug: 'pdf-to-png',
    icon: '🖼️',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-emerald-500 to-cyan-600',
  },
  {
    name: 'PDF to SVG',
    description: 'Convert PDF pages into scalable vector SVG graphics suitable for responsive web design and crisp scaling.',
    slug: 'pdf-to-svg',
    icon: '📐',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-cyan-500 to-blue-600',
  },
  {
    name: 'Electronic Invoice (Factur-X / ZUGFeRD)',
    description: 'Create and parse standardized electronic invoices with embedded XML data compliant with European & global e-invoicing laws.',
    slug: 'electronic-invoice',
    icon: '🧾',
    category: "Office",
    categorySlug: "office",
    color: 'from-green-600 to-emerald-700',
  },
  {
    name: 'PDF to Word (.docx)',
    description: 'Convert PDF documents into editable Microsoft Word (.docx) documents with intact headings, paragraphs, and lists.',
    slug: 'pdf-to-word',
    icon: '📝',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-blue-600 to-indigo-700',
  },
  {
    name: 'Word to PDF (.docx to PDF)',
    description: 'Convert Microsoft Word DOCX files into polished, standardized PDF documents with zero formatting drift.',
    slug: 'word-to-pdf',
    icon: '📄',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-indigo-600 to-purple-700',
  },
  {
    name: 'PDF to Excel (.xlsx)',
    description: 'Detect and extract tabular data, matrices, and financial schedules from PDF files into downloadable Excel spreadsheets.',
    slug: 'pdf-to-excel',
    icon: '📊',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-emerald-600 to-green-700',
  },
  {
    name: 'Excel to PDF (.xlsx to PDF)',
    description: 'Convert Excel spreadsheets, CSV data, and financial tables into paginated, publication-ready PDF reports.',
    slug: 'excel-to-pdf',
    icon: '📈',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-teal-600 to-emerald-700',
  },
  {
    name: 'HEIC to JPG / PNG',
    description: 'Convert Apple iPhone & iPad HEIC / HEIF photos into universal JPG and PNG formats directly in the browser.',
    slug: 'heic-to-jpg',
    icon: '📸',
    category: "Media",
    categorySlug: "media",
    color: 'from-rose-500 to-orange-600',
  },
  {
    name: 'PDF to PowerPoint (.pptx)',
    description: 'Convert PDF presentation slides into customizable PowerPoint presentation decks with 1-click export.',
    slug: 'pdf-to-powerpoint',
    icon: '📽️',
    category: "Convert from PDF",
    categorySlug: "convert-from-pdf",
    color: 'from-orange-600 to-red-600',
  },
  {
    name: 'All-in-One Universal Office Converter',
    description: 'Convert any Word (.docx), Excel (.xlsx), PowerPoint (.pptx), PDF, CSV, or TXT file into your desired format.',
    slug: 'universal-office-converter',
    icon: '🔄',
    category: "Office",
    categorySlug: "office",
    color: 'from-indigo-600 via-purple-600 to-pink-600',
  },
  {
    name: 'Word to HTML (.docx to HTML)',
    description: 'Convert Microsoft Word (.docx) documents into clean, semantic HTML code with preserved headings, lists, and tables.',
    slug: 'word-to-html',
    icon: '🌐',
    category: "Office",
    categorySlug: "office",
    color: 'from-blue-600 to-cyan-600',
  },
  {
    name: 'Word to TXT (.docx to Plain Text)',
    description: 'Extract raw plain text from Microsoft Word (.docx and .doc) files with live character and word counters.',
    slug: 'word-to-txt',
    icon: '📝',
    category: "Office",
    categorySlug: "office",
    color: 'from-sky-600 to-blue-700',
  },
  {
    name: 'Word to Markdown (.docx to .md)',
    description: 'Convert Microsoft Word (.docx) files into clean GitHub-flavored Markdown with headers, bold, italics, and code.',
    slug: 'word-to-markdown',
    icon: '📑',
    category: "Office",
    categorySlug: "office",
    color: 'from-slate-700 to-indigo-800',
  },
  {
    name: 'Online Word Document Editor',
    description: 'Full-featured in-browser Word document editor. Open, edit, format typography, and export to DOCX, HTML, or PDF.',
    slug: 'word-editor',
    icon: '📄',
    category: "Office",
    categorySlug: "office",
    color: 'from-blue-700 to-indigo-800',
  },
  {
    name: 'Excel to CSV (.xlsx to .csv)',
    description: 'Convert Microsoft Excel (.xlsx, .xls) workbooks and sheets into clean CSV or TSV files with custom delimiters.',
    slug: 'excel-to-csv',
    icon: '📊',
    category: "Office",
    categorySlug: "office",
    color: 'from-emerald-600 to-teal-700',
  },
  {
    name: 'Excel to JSON (.xlsx to .json)',
    description: 'Transform Excel spreadsheets into structured JSON arrays of objects with syntax coloring and schema validation.',
    slug: 'excel-to-json',
    icon: '📦',
    category: "Office",
    categorySlug: "office",
    color: 'from-green-600 to-emerald-700',
  },
  {
    name: 'Excel to HTML (.xlsx to HTML Table)',
    description: 'Convert Excel (.xlsx) and CSV spreadsheets into responsive, styled HTML table markup ready for web embedding.',
    slug: 'excel-to-html',
    icon: '🏷️',
    category: "Office",
    categorySlug: "office",
    color: 'from-teal-600 to-cyan-700',
  },
  {
    name: 'PowerPoint to PDF (.pptx to PDF)',
    description: 'Convert Microsoft PowerPoint (.pptx) presentation decks into clean, standardized, printable PDF documents.',
    slug: 'powerpoint-to-pdf',
    icon: '🎯',
    category: "Convert to PDF",
    categorySlug: "convert-to-pdf",
    color: 'from-orange-600 to-amber-700',
  },
  {
    name: 'PowerPoint to Images (.pptx to JPG/PNG)',
    description: 'Convert PowerPoint (.pptx) slides into high-resolution JPG or PNG images with individual and 1-click ZIP downloads.',
    slug: 'powerpoint-to-images',
    icon: '🖼️',
    category: "Office",
    categorySlug: "office",
    color: 'from-amber-500 to-rose-600',
  },
  {
    name: 'PowerPoint Viewer & Slideshow',
    description: 'Open and present PowerPoint (.pptx) presentation slides directly in your browser with full-screen slideshow mode.',
    slug: 'powerpoint-viewer',
    icon: '📽️',
    category: "Office",
    categorySlug: "office",
    color: 'from-red-600 to-orange-600',
  },
  {
    name: 'PowerPoint to HTML (.pptx to Web Deck)',
    description: 'Convert PowerPoint (.pptx) presentations into responsive HTML5 web slide decks with keyboard navigation.',
    slug: 'powerpoint-to-html',
    icon: '💻',
    category: "Office",
    categorySlug: "office",
    color: 'from-purple-600 to-pink-600',
  },
];

